services:
  backend:
    build:
      context: $BACKEND_LOCAL_CODE_PATH
      dockerfile: Dockerfile
    image: avpps/utdee-backend:latest
    ports:
      - 8000:8000
    restart: always
    environment:
      TZ: $TZ
      PORT: 8000
      MONGO_URI: mongodb://mongodb:27017
      MONGO_TEST_DB: $MONGO_INITDB_DATABASE
      MONGO_TEST_USER: $MONGO_TEST_USER
      MONGO_TEST_USER_PASSWORD: /run/secrets/mongo_test_user_password
      GUNICORN_CERT: /run/secrets/backend_cert
      GUNICORN_KEY: /run/secrets/backend_key
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    secrets:
      - mongo_test_user_password
      - backend_cert
      - backend_key
    volumes:
      - type: bind  # TODO: binding for local dev purposes only
        source: $BACKEND_LOCAL_CODE_PATH
        target: /app/
        bind:
          propagation: shared
    depends_on:
      - mongo
    networks:
      - tempo-network
      - mongo

  mongo:
    image: mongo:6.0.10
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD  # TODO
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_TEST_USER: $MONGO_TEST_USER
      MONGO_TEST_USER_PASSWORD: $MONGO_TEST_USER_PASSWORD  # TODO
    volumes:
      - mongo:/data/db
      - ./services/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    secrets:
      - mongo_initdb_root_password
      - mongo_test_user_password
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD  # TODO
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGO_EXPRESS_LOGIN
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGO_EXPRESS_PASSWORD  # TODO
    ports:
      - 8081:8081
    depends_on:
      - mongo
    secrets:
      - mongo_express_password
    networks:
      - mongo

secrets:
  mongo_initdb_root_password:
    file: ./.secrets/mongo_initdb_root_password.txt
  mongo_test_user_password:
    file: ./.secrets/mongo_test_user_password.txt
  mongo_express_password:
    file: ./.secrets/mongo_express_password.txt
  backend_cert:
    file: ./.secrets/backend_cert.pem
  backend_key:
    file: ./.secrets/backend_key.pem

volumes:
  mongo:

networks:
  tempo-network:
    external:
      name: tempo-network
  mongo: