[tool.poetry]
name = "utdee"
version = "0.1.0"
description = ""
authors = ["avpps <avppsdev@gmail.com>"]

[tool.poetry.dependencies]
python = "3.11.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core==1.6.1"]
build-backend = "poetry.core.masonry.api"
